spring.main.web-application-type=none

product.import.enabled=true
product.import.rollback.enabled=false
recommendation.import.enabled=false
product.search.backfill.enabled=false
product.data-model.backfill.enabled=false
