spring.main.web-application-type=none

product.import.enabled=false
product.import.rollback.enabled=false
recommendation.import.enabled=false
product.search.backfill.enabled=true
product.search.mode=locate
product.search.logging.enabled=false
product.data-model.backfill.enabled=false
