spring.main.web-application-type=none

product.import.enabled=false
product.import.rollback.enabled=false
recommendation.import.enabled=false
product.search.backfill.enabled=false
product.search.evaluation.enabled=true
product.search.logging.enabled=false
product.search.mode=${PRODUCT_SEARCH_EVALUATION_MODE:fulltext}
product.data-model.backfill.enabled=false
