spring.main.web-application-type=none

product.import.enabled=false
product.import.rollback.enabled=true
recommendation.import.enabled=false
product.search.backfill.enabled=false
product.data-model.backfill.enabled=false
